WIP: Move helper methods from ReTheme to jsutils
simpleviewinc/keg-hub pull request #115
Opened 2021-01-07 00:41 UTC by lancetipton

## Context

* There were a few methods that should go into jsutils instead of ReTheme
* We should move them to jsutils

## Goal

* Move some methods form ReTheme to  jsutils 

## Updates
* Added a couple array helper methods
  * `flatArr` - Makes an array with arrays flat 
  * `ensureArr` - Ensures a variable is an array
* Migrated some methods from ReTheme to jsutils
  *  `hashstring` - Converts a string in to a hash
  * `hyphenator` - Converts a CSS in JS rule  string to standard CSS style with hyphens  
* Updated calls to `hasDomAccess` to use the jsutils version

## Testing

**Test 1**
* Pull the PR => `keg pr <>`
* Run tests for jsutils => `keg jsutils && yarn test`
* Run tests for ReTheme => `keg retheme && yarn test`

**Test 2**
* Run this Keg-Components docker package => ``
  * This has the jsutils and  ReTheme changes synced into it
* Navigate to <> in your browser
* Ensure all components render as expected

2021-01-07 22:05 UTC, mpcarolin requested changes
ReTheme's image passed testing. When I ran the `keg-components` one though, I encountered this for several of the components:

![image](https://user-images.githubusercontent.com/9517356/103950237-c4935200-50f9-11eb-8050-a08f5dc49dae.png)

Doesn't really seem related to this at all, so not sure what's happening there.

I also left one code suggestion regarding the hash function.

2021-01-07 22:17 UTC, lancetipton commented on repos/jsutils/src/string/hashString.js
> +export const hashString = (str, maxLength=0) => {
Yah, that works, I'll update to that

2021-01-07 22:20 UTC, lancetipton commented on repos/jsutils/src/string/hashString.js
> +export const hashString = (str, maxLength=0) => {
Actually looking at it, why would I ever want a 0 length string? 
I think it's correct the way it is. Makes no sense to even call it if maxLength is set to 0

2021-01-07 23:51 UTC, mpcarolin approved these changes
Looks good 👍🏼

2021-01-08 00:44 UTC, daniel112 approved these changes
all unit test passed and the storybook looks good

2021-01-08 01:22 UTC, merged