WIP: Removed unused repos
simpleviewinc/keg-hub pull request #123
Opened 2021-01-11 18:26 UTC by lancetipton

**Ticket**: [issue_id](link_to_jira_ticket)

## Context

* Remove unused repos
* Move Keg-CLI to it's own repo

## Updates

* Remove `retheme/app`, `keg-regulator` and `keg-cli`

## Testing

2021-01-11 21:06 UTC, daniel112 reviewed
Im consistently running into an error during `keg cli test` step.
other test steps are good though

2021-01-11 21:44 UTC, mpcarolin requested changes
Testing all looked good until step 3, when this unit test failed for me:
![image](https://user-images.githubusercontent.com/9517356/104241776-6dec8780-541b-11eb-8c36-6bb1f37058c0.png)

* I ran it a few times to make sure it wasn't something random; same results
* keg-base image was definitely created and tagged to development: 
<img width="969" alt="image" src="https://user-images.githubusercontent.com/9517356/104241878-86f53880-541b-11eb-91cd-34fd7966d873.png">

2021-01-12 17:39 UTC, daniel112 approved these changes

2021-01-12 20:48 UTC, mpcarolin approved these changes

2021-01-12 21:04 UTC, merged