WIP: ReTheme Hook Updates
simpleviewinc/keg-hub pull request #77
Opened 2020-11-23 20:51 UTC by lancetipton

**Ticket**: [ZEN-467](https://jira.simpleviewtools.com/browse/ZEN-467)

## Context

* When we recently upgrade to rnw v14, it introduced a new way for hover to work
* One approach is to use a new `Pressable` component that passes the hover boolean to child components
  * Unfortunately This introduces another dom-element that could interfere with styling.
  * We should update the `useThemeHover` hook to work with rnw 14, ensuring all our existing components will work without needing changes and without `Pressable` interfering with styling

## Goal
  * Fix the retheme hooks so the work with the updated version of `react-native-web`
  * Update the hooks in a way so the ReTheme consumers do not need to change their code
  * Ensure the hooks work without adding extra dom-nodes

## Updates

* `repos/re-theme/app/package.json`
  * Updated dependencies for the app
* `repos/re-theme/configs/jest.config.js
  * Moved out of the package.json
* `repos/re-theme/configs/buildHook.js`
  * Cleaned up the build hook to only run once
* `repos/re-theme/configs/rollup.config.js`
  * Cleaned up alias to be reusable
    * Now match how keg-components alias work
  * Updated react-native-web imports to use the esm imports
  * The CJS imports were being included in the bundle, so the code was being duplicated
    * These exports are now considered external, and will be imported from the consumers version of react-native-web
* `repos/re-theme/src/styleInjector/reactNativeWeb.js`
  * Updated to use the `esm` imports instead of the `cjs` versions
  * This allows the imports to be external, and not be included in the bundle
  * This way the `react-native-code` that's imported in not duplicated
* `repos/re-theme/container/*`
  * Updated the container files to use the `KEG_PROXY_PORT` for registering with the `keg-proxy`
* `repos/re-theme/scripts/dockerBuild.sh`
  * Added a docker build script for building within the docker container
* `repos/re-theme/src/hooks/*`
  * Rewrote how the theme hooks work to make them work with the newer versions of react-native-web
    * They now use the dom element to apply the event handlers
    * This should allow them to be more maintainable long term
    * So we should not have to update them again if things change within `react-native-web`
* `repos/re-theme/src/hooks/usePointerState.js`
  * Added a new pointerState hook, that allows tracking the current state of a pointer ( mouse )
  * This is used by the `useThemeHook`, but also exported so it can be used in other places
    * Allows tracking `hover`, `active`, or `focus` states
* `repos/re-theme/src/hooks/hookFactory.js`
  * Removed some files no longer being used
* `repos/re-theme/src/hooks/nativeThemeHook.js`
  * Updated to use shallowEqual because it's faster
* `repos/re-theme/src/hooks/__tests__/*`
  * Added more tests for updated code
  * Fixed test the broke due to code changes
* `repos/re-theme/src/mocks/reactHooks.js`
  * Added mocks for react hooks so they can be reused
  * I eventually want to move things like this in to a `jest` helper repo
  * But that's down the road, and this works for now

## Testing

**Test 1**
* Run the retheme docker package => `keg retheme pack run docker.pkg.github.com/simpleviewinc/keg-packages/retheme:zen-467-retheme-hook-updates`
  * Navigate to http://retheme-zen-467-retheme-hook-updates.local.kegdev.xyz/
  * Open each of the hooks, and ensure they work as expexted

**Test 2**
* Attach to the running docker container => `keg d att package-retheme-zen-467-retheme-hook-updates`
* Run the tests => `yarn test`
  * Ensure all tests pass
 

 TODO: Add tap tests

2020-11-30 19:25 UTC, daniel112 requested changes
The buttons work now, but I'm still seeing a similar issue on other components that uses `Touchable` both in keg-components and the tap

2020-11-30 19:25 UTC, daniel112 commented on repos/keg-components/src/components/touchable/touchable.native.js
> +import { useClassOnPressIn } from 'KegClassOnPressIn'
marking this file for reference.
For any other component that uses `Touchable` directly, a similar bug still occurs, though it's slightly different than how it occured before.

* it sometimes removes the classNames on `keg-touchable` 
* it happens occasionally even if you don't click + drag

on `keg-components:` 
* `textToggle` component
    * [gif](https://user-images.githubusercontent.com/3317835/100653453-aa4da380-3305-11eb-9c92-825c7aa9f9a6.gif)

* `Touchable` component
    * [gif](https://user-images.githubusercontent.com/3317835/100653200-49be6680-3305-11eb-8470-44f1be64f361.gif)

on `tap evf`:
* Mobile view - expandable session
   * the grid item is wrapped with `Touchable`
   * when you click + drag to the side, the styles on the `Touchable` component dissapears
   * [gif](https://user-images.githubusercontent.com/3317835/100654021-77f07600-3306-11eb-9279-3aca34291666.gif)
* Session Links
   * click + drag still occurs, but unlike before, i'm able to bring the styles back if I click on the link again
   * [gif](https://user-images.githubusercontent.com/3317835/100654323-d9184980-3306-11eb-8dbc-49f0b02bc6f2.gif)

2020-11-30 21:21 UTC, mpcarolin requested changes
Looks like it fixed it in some cases, but I was still able to reproduce the old issue.

Dragging upwards from a presenter name, for example: 
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/9517356/100666966-2c929380-3317-11eb-9f70-b23e62b21d1d.png">

Also, on Safari (but not Firefox), dragging on the buttons in keg-components caused the button background to disappear and only the name to show (ping me if you want to see a video I recorded of this)

Also, I had one unit test fail with `usePointerState`: 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/9517356/100667136-577ce780-3317-11eb-9814-bcd3b65d7e7d.png">

Finally, I just had a few code requests in my comments.

2020-11-30 21:26 UTC, lancetipton commented on repos/re-theme/src/hooks/useThemeState.js
> +      ref: options.ref || useRef(null),
Ahh good catch sir, completely missed that one.

2020-11-30 21:38 UTC, lancetipton commented on repos/keg-components/src/components/touchable/touchable.native.js
> +  const handelPressIn = useClassOnPressIn(onPressIn, defClass, className)
Updated

2020-11-30 21:44 UTC, lancetipton commented on repos/re-theme/src/hooks/useThemeState.js
> +      ref: options.ref || useRef(null),
Updated

2020-11-30 21:51 UTC, lancetipton commented on repos/re-theme/src/hooks/usePointerState.js
> + * @param {Object} options - Contains callbacks and refs for the pointerState
Updated

2020-11-30 21:51 UTC, lancetipton commented on repos/re-theme/src/hooks/useThemeState.js
> +   * @param {*} onValue - Value to return when the state is on
Updated

2020-11-30 21:51 UTC, lancetipton commented on repos/re-theme/src/hooks/usePointerState.js
> + * @param {string} pointerState - pointer state to track
Updated

2020-12-01 19:41 UTC, daniel112 approved these changes
looks good to me

2020-12-02 17:44 UTC, mpcarolin approved these changes
As discussed, the button issues will be handled in the Pressable ticket.

Everything else looks good 👍

2020-12-02 18:49 UTC, merged